title: "The Curious Engineer"
subtitle: "Version 2.0"
email:
description: >- # this means to ignore newlines until "baseurl:"
  A blog about various problems and their solutions.
github_username: raven4ever
minimal_mistakes_skin: default
search: true

domain: raven4ever.github.io
url: https://raven4ever.github.io
repository: "raven4ever/raven4ever.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
logo: "/assets/images/curious-logo.png"

# Outputting
permalink: /blog/:title/
paginate: 7 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Bucharest

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Adrian"
  avatar: "/assets/images/bio-photo.png"
  bio: "A simple engineer curious to explore the technical world."
  location: "Bucharest, Romania"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/raven4ever"
    - label: "Ko-fi"
      icon: "fas fa-mug-hot"
      url: "https://ko-fi.com/raven4ever"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true
      related: true
      author_profile: false
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

tag_archive:
  type: liquid
  path: /tags/
